### ISSUE TITLE
The downloaded stable-diffusion-2-depth has an issue

### ISSUE THREAD

**Issue by lingzhenfei** [Quantuman134/TexPainter#8]
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    main(args)
  File "main.py", line 23, in main
    sd = StableDiffusionDepth(device=device, num_inference_steps=num_inference_steps)
  File "E:\code\TexPainter-main\stable_diffusion_depth.py", line 12, in __init__
    self.vae = AutoencoderKL.from_pretrained(library, subfolder="vae").to(device)
  File "C:\Users\Administrator\.conda\envs\TexPainter\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\TexPainter\lib\site-packages\diffusers\models\modeling_utils.py", line 804, in from_pretrained
    model_file = _get_model_file(
  File "C:\Users\Administrator\.conda\envs\TexPainter\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\TexPainter\lib\site-packages\diffusers\utils\hub_utils.py", line 309, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory stabilityai/stable-diffusion-2-depth.

**Comment by Quantuman134** [comment]
That seems like a problem of ckpt download. Have you tried using from_pretrained function download other model on huggingface?
